### ISSUE TITLE
applyInterceptors is calling `.then(undefined, undefined)`

### ISSUE THREAD

**Issue by mbroadst** [aurelia/fetch-client#41]
This a pretty annoying error that pops up when you use a bluebird drop in replacement for `Promise`. It seems to indicate that in this piece of code: https://github.com/aurelia/fetch-client/blob/master/src/http-client.js#L220, you actually end up passing `.then(undefined, undefined)` (rather than what I think you expect to be `.then(null, null)`?) if the interceptors don't exist.

**Comment by mbroadst** [comment]
sorry, this is the error:

```
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at http://localhost:9000/jspm_packages/npm/aurelia-fetch-client@1.0.0-beta.1.1.0/aurelia-fetch-client.js:240:20
    at Array.reduce (native)
    at applyInterceptors (http://localhost:9000/jspm_packages/npm/aurelia-fetch-client@1.0.0-beta.1.1.0/aurelia-fetch-client.js:236:33)
    at processRequest (http://localhost:9000/jspm_packages/npm/aurelia-fetch-client@1.0.0-beta.1.1.0/aurelia-fetch-client.js:224:12)
    at HttpClient.<anonymous> (http://localhost:9000/jspm_packages/npm/aurelia-fetch-client@1.0.0-beta.1.1.0/aurelia-fetch-client.js:125:21)
    at HttpClient.fetch (http://localhost:9000/jspm_packages/npm/aurelia-fetch-client@1.0.0-beta.1.1.0/aurelia-fetch-client.js:109:23)
    at Object.RestApi.hosts.statistics (http://localhost:9000/dist/services/rest-api.js:57:30)
    at OverviewStatistics.updateStatistics (http://localhost:9000/dist/overview/overview-statistics.js:55:29)
    at OverviewStatistics.attached (http://localhost:9000/dist/overview/overview-statistics.js:41:25)
    at Controller.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:2920:24)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:1044:24)
    at ViewSlot.add (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:1297:14)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.1.1/router-view.js:117:25
```

**Comment by mbroadst** [comment]
hmm, I have no idea what happened here. I tried this all again today more incrementally and now I'm not seeing any errors whatsoever... The only thing I haven't done in this run is update bluebird from 3.1.1 -> 3.3.1, there might be something there, but I can't imagine it would be this systematic of a problem.

Closing for now until I experience it again!
