### ISSUE TITLE
OPTIONS requests with none OK statusCode are breaking promise 

### ISSUE THREAD

**Issue by dweber019** [aurelia/fetch-client#82]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
If I try to request a URL path which does not exist the OPTIONS call will return with 404. This will break the promise chain.

I have the following setup of the fetch client:
```
this.restClient.getHttpClient().configure(config => {
      config
        .useStandardConfiguration();
    });
```

If I do the following:
```
this.httpClient.fetch('https://google.ch/7');
```

then I get this type error in the catch handler as reason passed:
```
TypeError: Failed to fetch
    at applyInterceptors (http://localhost:9000/app.bundle.js:32332:14)
    at processResponse (http://localhost:9000/app.bundle.js:32315:10)
    at http://localhost:9000/app.bundle.js:32230:16
From previous event:
    at http://localhost:9000/app.bundle.js:32229:22
From previous event:
    at HttpClient.<anonymous> (http://localhost:9000/app.bundle.js:32217:62)
    at HttpClient.fetch (http://localhost:9000/app.bundle.js:32201:21)
    at RestClient.fetchGet (http://localhost:9000/app.bundle.js:83603:40)
    at RestClient.findAll (http://localhost:9000/app.bundle.js:83580:21)
    at PoiRestService._callee$ (http://localhost:9000/app.bundle.js:83447:78)
    at tryCatch (http://localhost:9000/aurelia-bootstrap.bundle.js:10085:40)
    at Generator.invoke [as _invoke] (http://localhost:9000/aurelia-bootstrap.bundle.js:10359:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:9000/aurelia-bootstrap.bundle.js:10118:21)
    at http://localhost:9000/app.bundle.js:83427:65
From previous event:
    at __awaiter (http://localhost:9000/app.bundle.js:83407:12)
    at PoiRestService.getAll (http://localhost:9000/app.bundle.js:83442:16)
    at http://localhost:9000/app.bundle.js:82662:42
From previous event:
    at PoiDistributionEntityService.getPoisFuzzy (http://localhost:9000/app.bundle.js:82661:52)
    at Selectize.load (http://localhost:9000/app.bundle.js:78929:57)
    at Selectize.<anonymous> (http://localhost:9000/app.bundle.js:80086:8)
    at Selectize.load (http://localhost:9000/app.bundle.js:80242:7)
    at Selectize.onSearchChange (http://localhost:9000/app.bundle.js:80085:9)
    at http://localhost:9000/app.bundle.js:79274:8
```

**Expected/desired behavior:**
I would expect to get the Response of the OPTIONS request. As the normal fetch implementation does => https://jsbin.com/kokaledita/edit?js,console

Most backends don't respond with a 404 from a OPTIONS request.

**Comment by avaisane** [comment]
We are facing this problem also. Can't react on response interceptor.

 .withInterceptor({response: that.rejectOnError})
 rejectOnError(response){
       // Exception thrown before this line.
       console.log('response status', response.status);
        if(!response.ok){
            debugger;
            throw response;
        }
        return response;
    }

**Comment by EisenbergEffect** [comment]
@bryanrsmith Any thoughts on this?

**Comment by bryanrsmith** [comment]
`config.useStandardConfiguration();` adds an interceptor that causes unsuccessful responses to result in a rejection. Try using a `responseError` interceptor, or stop using that configuration if that's not the behavior you want.

**Comment by EisenbergEffect** [comment]
Thanks @bryanrsmith !
